# docker compose up --build keycloak
# https://www.keycloak.org/server/db
version: "3.1"
services:
  keycloak:
    container_name: keycloak-pro
#    image: keycloak-postgres
    build: ./build
#    command: start --optimized --hostname-strict=false
#    command: start --optimized --hostname-strict=false --proxy edge
    command: start --optimized --hostname-strict=false --proxy edge --db-url=jdbc:postgresql://postgres:5432/keycloak --db-username=keycloak --db-password=P@ssw0rd
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - TZ=Asia/Bangkok
      - KC_FEATURES=admin2 

#      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
#      - KC_DB_USERNAME=keycloak
#      - KC_DB_PASSWORD=P@ssw0rd
    ports:
      - 9080:8080 
      - 9443:8443
    depends_on:
      - postgres
  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=P@ssw0rd
      - TZ=Asia/Bangkok
#    ports:
#      - 5432:5432
    volumes:
      - ./pgtest-volume:/var/lib/postgresql/data

