# docker compose -f docker-compose.dev.yaml up
version: "3.1"
services:
  keycloak:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:20.0.3
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - TZ=Asia/Bangkok
    volumes:
#      - ./themes:/opt/keycloak/themes:rw
      - ./data:/opt/keycloak/data:rw
    ports:
      - 9080:8080
