


# docker compose -f docker-compose.test.yaml up --build keycloak
version: "3.1"
services:
  keycloak:
    container_name: keycloak-test
    image: quay.io/keycloak/keycloak:20.0.3
    command: start --db-url-host postgres --proxy edge --hostname-strict=false

    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - KC_FEATURES=admin2 
      - TZ=Asia/Bangkok
      # build
      - ENV KC_HEALTH_ENABLED=true
      - ENV KC_METRICS_ENABLED=true
      - KC_DB=postgres
      # run
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=P@ssw0rd
#    volumes:
#      - ./themes:/opt/keycloak/themes:rw
    ports:
      - 9080:8080 
#      - 9443:8443

    depends_on:
      - postgres
  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=P@ssw0rd
      - TZ=Asia/Bangkok
#    ports:
#      - 5432:5432
    volumes:
      - ./pgtest-volume:/var/lib/postgresql/data

