version: "3"
services:
  orchard-cms:
    container_name: orchardcms
    image: orchardproject/orchardcore-cms-linux:latest
    ports:
      - 22080:80
    restart: unless-stopped
    volumes:
      - ./App_Data:/app/App_Data
